from pathlib import Path
import sys
output = sys.argv[1]

vertex_shader = sys.argv[2]
fragment_shader = sys.argv[3]
shaders_dir= sys.argv[4]

shaders = "//THIS FILE IS AUTOGENERATED\n"
shaders += "const char* vertexShaderSourceMain = R\"(\n";

# main vertex shader
with open(vertex_shader) as file:
    shaders += file.read();
    shaders += ")\";\n"

#yuv2rgb glsl matrix
yuv2rgb = """const mat4 yuv2rgb = mat4(
    vec4(  1.1644,  1.1644,  1.1644,  0.0000 ),
    vec4(  0.0000, -0.2132,  2.1124,  0.0000 ),
    vec4(  1.7927, -0.5329,  0.0000,  0.0000 ),
    vec4( -0.9729,  0.3015, -1.1334,  1.0000 )
);\n"""

uniforms = """
in vec2 vTexCoord;
uniform sampler2D uTexY_from;
uniform sampler2D uTexC_from;
uniform sampler2D uTexY_to;
uniform sampler2D uTexC_to;
out vec4 oColor;
\n
"""

functions = """
vec4 getFromColor(vec2 uv) {
  return yuv2rgb * vec4(
    texture(uTexY_from, uv).x,
    texture(uTexC_from, uv).xy,
    1.0
  );
}

vec4 getToColor(vec2 uv) {
  return yuv2rgb * vec4(
    texture(uTexY_to, uv).x,
    texture(uTexC_to, uv).xy,
    1.0
  );
}\n
"""

#main fragment shader
with open(fragment_shader) as file:
    shaders += "const char* fragmentShaderSourceMain = R\"(\n"
    shaders += file.read().replace("@YUV2RGB",yuv2rgb)
    shaders += ")\";\n"

#general transition fragment shaders
shaders_path = Path(shaders_dir)
for p in shaders_path.iterdir():
    if(p.name == "main.vert" or p.name == "main.frag"):
        continue
    shaders += f"const char* {p.name.rstrip(".frag")}TransitionFragmentShaderSource = R\"(\n"
    shaders += p.read_text().replace("@YUV2RGB",yuv2rgb).replace("@UNIFORMS",uniforms).replace("@FUNCTIONS",functions)
    shaders += ")\";\n"

with open(output,"w") as file:
    file.write(shaders)
